SELECT DISTINCT A.CART_ID
FROM CART_PRODUCTS as A JOIN CART_PRODUCTS as B 
ON A.CART_ID = B.CART_ID
WHERE (A.NAME = 'Milk' and B.NAME = 'Yogurt') or (B.NAME = 'Milk' and A.NAME = 'Yogurt')
ORDER BY A.CART_ID